{% set name = "scramp" %}
{% set version = "1.4.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: bd018fabfe46343cceeb9f1c3e8d23f55770271e777e3accbfaee3ff0a316e71

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: True  # [py<310]

requirements:
  host:
    - pip
    - python
    - hatchling
    - versioningit
  run:
    - python
    - asn1crypto >=1.5.1

test:
  source_files:
    - test/test_scramp.py
  imports:
    - scramp
  commands:
    - pip check
    - pytest -v test/test_scramp.py
  requires:
    - pip
    - pytest
    - pytest-mock

about:
  home: https://codeberg.org/tlocke/scramp
  summary: A pure-Python implementation of the SCRAM authentication protocol
  license: MIT
  license_family: MIT
  license_file: LICENSE
  description: |
    A Python implementation of the SCRAM authentication protocol defined by
    RFC 5802 and RFC 7677.
  dev_url: https://codeberg.org/tlocke/scramp
  doc_url: https://codeberg.org/tlocke/scramp/src/branch/main/README.md

extra:
  recipe-maintainers:
    - nicolas-geniteau
    - maximerihouey
    - ncolomer
